// Fiches des sociétés d'Aurelys : ce qu'elles font et leur histoire, en quelques phrases. Tout est inventé.
export const STORIES = {
  NXR: { what: "Puces et intelligence artificielle", since: "2011 · Port-Aurel",
    story: "Deux étudiantes en mathématiques, Lena Kost et Aya Merin, lancent Nexora dans un garage du quartier des docks. Leur assistant « Nexo » équipe aujourd'hui un téléphone sur deux du pays. L'action a été multipliée par vingt en cinq ans : beaucoup pensent que c'est trop." },
  PXF: { what: "Jeux vidéo", since: "2004 · Valmeyre",
    story: "Son jeu culte « Lanterne », vendu à 40 millions d'exemplaires, fait encore vivre le studio. Depuis, chaque sortie est un pari : un succès fait bondir l'action, un flop la fait plonger." },
  OMB: { what: "Médicaments contre les maladies rares", since: "1962 · Haut-Ombre",
    story: "Le laboratoire a commencé par des sirops contre la toux, dans les montagnes du Haut-Ombre. Il cherche aujourd'hui des traitements contre les maladies rares, baptisés OMB suivi d'un numéro. Un essai réussi peut doubler sa valeur, un échec la faire fondre." },
  HLV: { what: "Électricité : barrages, éolien, gaz", since: "1998 · Brennes",
    story: "Ancienne compagnie publique de l'électricité, privatisée en 1998. Barrages, éoliennes en mer et une vieille centrale à gaz. Elle verse un gros dividende chaque année et les retraités l'adorent. Rien d'excitant, et c'est voulu." },
  FRC: { what: "Acier pour les rails, les ponts et les voitures", since: "1891 · Grise-Vallée",
    story: "Les hauts-fourneaux de Ferrocap fument depuis plus d'un siècle à Grise-Vallée. Quand l'économie tourne, les commandes d'acier affluent. Quand elle cale, Ferrocap cale aussi." },
  VLS: { what: "Voitures électriques", since: "2015 · Port-Aurel",
    story: "Ilan Varesko l'a créée pour faire « des voitures électriques plus belles que les autres ». L'usine géante tourne à plein, mais chaque nouveau modèle arrive en retard. L'action suit l'humeur de son patron, très actif sur les réseaux." },
  BCS: { what: "Banque et crédit", since: "1847 · Castellane",
    story: "La banque de la famille Castellane servait les grandes fortunes, puis tout le pays. Elle gagne plus quand les taux montent. Son service d'analyse, dirigé par Sofia Delmar, est écouté par toute la place. Une rumeur sur ses comptes suffit à faire trembler le marché." },
  MRV: { what: "Transport maritime de conteneurs", since: "1923 · Port-Aurel",
    story: "Ses 140 porte-conteneurs relient Aurelys au reste du monde. Son point faible : le détroit de Varn. Quand il se ferme, tout s'arrête." },
  GTR: { what: "Céréales et farine", since: "1975 · Plaines du Sud",
    story: "Une coopérative de céréaliers devenue un groupe agroalimentaire, connu pour sa farine « Épi d'or ». Son destin se joue dans le ciel : une sécheresse fait chuter l'action, une belle récolte la relève." },
  LMR: { what: "Supermarchés", since: "1958 · Lisère",
    story: "900 magasins, dans chaque ville du pays. On y fait ses courses même en pleine crise : c'est l'action qu'on garde quand tout va mal. Peu de marge, mais des clients fidèles." },
  SLM: { what: "Mine de lithium pour les batteries", since: "2018 · Sel-Rouge",
    story: "Une petite société qui exploite un gisement de lithium dans le désert de Sel-Rouge. Vélisse est son premier client. Peu d'actions s'échangent : un seul gros acheteur peut faire bondir le cours. Le Kraken l'a bien compris." },
  KST: { what: "Avions et hélicoptères", since: "1934 · Aérodrome d'Orme",
    story: "Kestrel construit des avions depuis les débuts de l'aviation d'Aurelys et équipe l'armée de l'air. Ses contrats durent des années : un grand contrat d'État peut remplir l'usine pour dix ans." },
  OND: { what: "Plateforme de streaming en direct", since: "2016 · Port-Aurel",
    story: "Trois anciens commentateurs de jeux vidéo ont lancé Ondéo pour diffuser leurs parties depuis une cave de Port-Aurel. Ses revenus suivent l'audience des lives : quand les spectateurs affluent, la publicité se vend mieux." },
};
